# QThermalMPS test suite.
#
# Ordered as a gate sequence: each file assumes the ones above it pass, so a
# failure high up explains the failures below it rather than adding to them.
#
#   layout        wire conventions (a contract with the Python encoder)
#   sites         the ancilla-statistics decision, as a numerical claim
#   hamiltonian   the MPO IS H -- checked against a by-hand construction
#   purification  rho(0) = P/dim exactly
#   observables   read-out against dense linear algebra
#   evolve        the ladder against exact thermodynamics
#
# Tests that need `results/*.h5` skip themselves with a message when the file
# is absent: those are gitignored and must be regenerated by the Python
# pipeline (see CLAUDE.md), so a fresh clone runs everything else.
#
#     julia --project=. -e 'using Pkg; Pkg.test()'
#     julia -t 8 --project=. test/runtests.jl        # faster, threaded

using Test
using LinearAlgebra
using Random

include("testutils.jl")

@testset "QThermalMPS" begin
    @testset "layout" begin
        include("test_layout.jl")
    end
    @testset "sites" begin
        include("test_sites.jl")
    end
    @testset "hamiltonian" begin
        include("test_hamiltonian.jl")
    end
    @testset "purification" begin
        include("test_purification.jl")
    end
    @testset "observables" begin
        include("test_observables.jl")
    end
    @testset "evolve" begin
        include("test_evolve.jl")
    end
    @testset "fused" begin
        include("test_fused.jl")
    end
    @testset "openshell" begin
        include("test_openshell.jl")
    end
end
